services:
  - type: web
    name: fluxvpn-bot
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_ID
        value: "6049379160"
      - key: ADMIN_USERNAME
        value: "zrdws"
      - key: CRYPTO_BOT_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
