TEXTS = {
"ru": {
"language":"Выбери язык интерфейса",
"language_saved":"✅ Язык сохранён",
"home":"<b>FluxVPN</b>\n━━━━━━━━━━━━\nПривет, <b>{name}</b>\n\n{subscription}\nБаланс: <b>{balance:.0f} ₽</b>\nРефералы: <b>{referrals}</b> · доход <b>{earned:.0f} ₽</b>",
"sub_active":"{plan}: <b>активен</b>\nОсталось: <b>{days} дн.</b> · до <code>{until}</code>",
"sub_inactive":"Подписка: <b>неактивна</b>",
"trial_ok":"✅ Пробный период активирован на 7 дней",
"trial_used":"Пробный период уже использован",
"already_active":"Подписка уже активна",
"active_required":"Нужна активная подписка",
"buy":"<b>Выбор тарифа</b>\n\nФиксированный срок или любое количество дней:",
"checkout":"<b>Оформление</b>\nСрок: <b>{days} дн.</b>\nЦена: <b>{price} ₽</b>{discount}\n\nВыбери способ оплаты:",
"custom_days":"Отправь количество дней от <b>{minimum}</b> до <b>{maximum}</b>",
"custom_days_error":"Нужно целое число от {minimum} до {maximum}",
"balance":"<b>Баланс</b>\nДоступно: <b>{balance:.0f} ₽</b>",
"balance_low":"Недостаточно средств. Нужно {price} ₽, доступно {balance:.0f} ₽",
"balance_paid":"✅ Оплачено с баланса: {price} ₽\nPremium активирован на {days} дн.",
"topup":"<b>Пополнение баланса</b>\nВыбери сумму:",
"manual_order":"<b>Заявка создана</b>\n{days} дн. · {price} ₽\n\nНапиши админу и отправь текст заказа:\n<code>{order}</code>",
"admin_order":"🛒 <b>Новый заказ</b>\nПользователь: <code>{user_id}</code> · {name}\nТариф: <b>{days} дн.</b>\nСумма: <b>{price} ₽</b>",
"order_paid_admin":"✅ Заказ подтверждён\n<code>{user_id}</code> · {days} дн. · {price} ₽",
"order_paid_user":"✅ Оплата подтверждена\nPremium активирован на <b>{days} дн.</b>",
"order_rejected_admin":"❌ Заказ отклонён · <code>{user_id}</code>",
"order_rejected_user":"❌ Заявка на {days} дн. отклонена. Если это ошибка — напиши в поддержку.",
"crypto_invoice":"<b>Счёт CryptoBot</b>\nК оплате: <b>{amount} ₽</b>",
"crypto_wait":"Платёж пока не найден. Подожди и проверь снова.",
"crypto_error":"Не удалось создать счёт. Используй баланс или оплату админу.",
"crypto_paid":"✅ Платёж найден\nPremium активирован на {days} дн.",
"topup_invoice":"<b>Счёт на пополнение</b> · {amount} ₽",
"topup_paid":"✅ Баланс пополнен на {amount} ₽",
"promo_prompt":"Отправь промокод одним сообщением",
"promo_invalid":"Промокод недействителен или закончился",
"promo_used":"Ты уже использовал этот промокод",
"promo_days":"✅ Промокод: +{value} дн. Premium",
"promo_balance":"✅ Промокод: +{value:.0f} ₽ на баланс",
"promo_percent":"✅ Скидка {value:.0f}% применится к следующей покупке",
"support_prompt":"Опиши проблему одним сообщением. Я создам тикет.",
"support_created":"✅ Тикет #{ticket_id} создан. Ответ придёт сюда.",
"support_admin":"🎫 <b>Тикет #{ticket_id}</b>\nОт: <code>{user_id}</code> · {name}\n\n{body}",
"support_reply":"💬 <b>Ответ поддержки · тикет #{ticket_id}</b>\n\n{body}",
"ticket_closed":"✅ Тикет #{ticket_id} закрыт",
"ticket_reply_prompt":"Отправь ответ для тикета #{ticket_id}",
"referral":"<b>Реферальная программа</b>\n\nЗа друга: <b>+{days} дней</b>\nС его покупок: <b>{percent}% на баланс</b>\nПриглашено: <b>{count}</b>\nЗаработано: <b>{earned:.0f} ₽</b>",
"servers":"<b>Доступные локации</b>\n\n{servers}",
"no_servers":"Пока нет активных локаций",
"banned":"🚫 Доступ ограничен\nПричина: {reason}",
"admin":"<b>FluxVPN · Админ-панель</b>\n━━━━━━━━━━━━\nПользователи: <b>{users}</b> · активны <b>{active}</b>\nPremium: <b>{premium}</b> · Trial: <b>{trial}</b>\nВыручка: <b>{revenue:.0f} ₽</b> · сегодня <b>{today:.0f} ₽</b>\nОткрытые тикеты: <b>{tickets}</b> · серверы <b>{servers}</b>",
"revenue":"<b>Статистика выручки</b>\n\nСегодня: <b>{today:.0f} ₽</b>\n7 дней: <b>{week:.0f} ₽</b>\n30 дней: <b>{month:.0f} ₽</b>\nЗа всё время: <b>{all_time:.0f} ₽</b>\nПлатежей: <b>{payments}</b>",
"users":"<b>Последние пользователи</b>\n\n{rows}",
"active_users":"<b>Активные подписки</b>\n\n{rows}",
"admin_user_id":"Отправь Telegram ID пользователя",
"admin_days":"Выбери срок:",
"admin_granted":"✅ Выдано {days} дн. пользователю <code>{user_id}</code>",
"admin_trial":"✅ Trial выдан пользователю <code>{user_id}</code>",
"admin_revoked":"✅ Подписка снята у <code>{user_id}</code>",
"admin_ban_reason":"Отправь причину блокировки",
"admin_banned":"✅ Пользователь <code>{user_id}</code> заблокирован",
"admin_unbanned":"✅ Пользователь <code>{user_id}</code> разблокирован",
"admin_balance":"Формат: <code>ID СУММА</code>\nНапример: <code>123456 200</code>",
"admin_balance_ok":"✅ Баланс <code>{user_id}</code> пополнен на {amount:.0f} ₽",
"admin_promo":"Формат:\n<code>CODE days 7 100</code>\n<code>CODE balance 100 50</code>\n<code>CODE percent 10 200</code>\nПоследнее число — лимит использований.",
"admin_promo_ok":"✅ Промокод <code>{code}</code> создан",
"admin_broadcast":"Отправь сообщение для рассылки",
"admin_broadcast_ok":"✅ Доставлено: {ok} · ошибок: {failed}",
"admin_server_name":"Отправь отображаемое имя сервера, например 🇩🇪 Germany",
"admin_server_config":"Теперь отправь строку VLESS/SS",
"admin_server_added":"✅ Сервер #{server_id} добавлен",
"admin_server_deleted":"✅ Сервер удалён",
"admin_devices_reset":"✅ Все устройства <code>{user_id}</code> заблокированы",
"not_found":"Ничего не найдено",
"cancelled":"Отменено",
"notify_2d":"⏰ <b>FluxVPN</b>\nДо окончания подписки 2 дня. Продли заранее, братан — без обрывов.",
"notify_1d":"⏰ <b>FluxVPN</b>\nОстался 1 день. Лучше продли подписку сейчас.",
"notify_1h":"⚡ <b>FluxVPN</b>\nОстался примерно час. Продли — и оставайся на связи.",
"notify_expired":"❌ <b>FluxVPN</b>\nПодписка закончилась. Продли, братан — доступ вернётся сразу.",
},
"en": {}
}
TEXTS["en"] = dict(TEXTS["ru"])
TEXTS["en"].update({
"language":"Choose interface language", "language_saved":"✅ Language saved",
"active_required":"Active subscription required", "cancelled":"Cancelled",
"not_found":"Nothing found", "banned":"🚫 Access restricted\nReason: {reason}"
})

def text(lang, key, **values):
    lang = lang if lang in TEXTS else "ru"
    template = TEXTS[lang].get(key, TEXTS["ru"].get(key, key))
    try: return template.format(**values)
    except Exception: return template
